config/routes.rb
Rails.application.routes.draw do

  resources :bars
  resources :cocktails
  resources :trucs
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "bars#index"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bar.rb
# == Schema Information
#
# Table name: bars
#
#  id         :bigint           not null, primary key
#  name       :string
#  adress     :string
#  city       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Bar < ApplicationRecord
    has_and_belongs_to_many :cocktails

    belongs_to :director, required: false
end

app/models/cocktail.rb
# == Schema Information
#
# Table name: cocktails
#
#  id          :bigint           not null, primary key
#  name        :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Cocktail < ApplicationRecord
    has_many :prices
    has_many :notes
    has_and_belongs_to_many :bars
    has_many :users, through: :notes
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :cocktail
  belongs_to :user
end

app/models/price.rb
# == Schema Information
#
# Table name: prices
#
#  id          :bigint           not null, primary key
#  value       :integer
#  cocktail_id :bigint           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Price < ApplicationRecord
  belongs_to :cocktail
end

app/models/truc.rb
# == Schema Information
#
# Table name: trucs
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Truc < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :notes
  has_many :cocktails, through: :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bar, only: %i[ show edit update destroy ]
  # GET /bars or /bars.json
  def index
    @bars = Bar.all
  end

  # GET /bars/1 or /bars/1.json
  def show
  end

  # GET /bars/new
  def new
    @bar = Bar.new
  end

  # GET /bars/1/edit
  def edit
  end

  # POST /bars or /bars.json
  def create
    @bar = Bar.new(bar_params)

    respond_to do |format|
      if @bar.save
        format.html { redirect_to bar_url(@bar), notice: "Bar was successfully created." }
        format.json { render :show, status: :created, location: @bar }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bars/1 or /bars/1.json
  def update
    respond_to do |format|
      if @bar.update(bar_params)
        format.html { redirect_to bar_url(@bar), notice: "Bar was successfully updated." }
        format.json { render :show, status: :ok, location: @bar }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bars/1 or /bars/1.json
  def destroy
    @bar.destroy

    respond_to do |format|
      format.html { redirect_to bars_url, notice: "Bar was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bar
      @bar = Bar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bar_params
      params.require(:bar).permit(:name, :adress, :city, cocktail_ids: [])
    end
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cocktail, only: %i[ show edit update destroy ]
  

  # GET /cocktails or /cocktails.json
  def index
    @cocktails = Cocktail.all
  end

  # GET /cocktails/1 or /cocktails/1.json
  def show
  end

  # GET /cocktails/new
  def new
    @cocktail = Cocktail.new
  end

  # GET /cocktails/1/edit
  def edit
  end

  # POST /cocktails or /cocktails.json
  def create
    @cocktail = Cocktail.new(cocktail_params)

    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to cocktail_url(@cocktail), notice: "Cocktail was successfully created." }
        format.json { render :show, status: :created, location: @cocktail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cocktails/1 or /cocktails/1.json
  def update
    respond_to do |format|
      if @cocktail.update(cocktail_params)
        format.html { redirect_to cocktail_url(@cocktail), notice: "Cocktail was successfully updated." }
        format.json { render :show, status: :ok, location: @cocktail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cocktails/1 or /cocktails/1.json
  def destroy
    @cocktail.destroy

    respond_to do |format|
      format.html { redirect_to cocktails_url, notice: "Cocktail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cocktail_params
      params.require(:cocktail).permit(:name, :description)
    end
    
end

app/controllers/trucs_controller.rb
class TrucsController < ApplicationController
  before_action :set_truc, only: %i[ show edit update destroy ]

  # GET /trucs or /trucs.json
  def index
    @trucs = Truc.all
  end

  # GET /trucs/1 or /trucs/1.json
  def show
  end

  # GET /trucs/new
  def new
    @truc = Truc.new
  end

  # GET /trucs/1/edit
  def edit
  end

  # POST /trucs or /trucs.json
  def create
    @truc = Truc.new(truc_params)

    respond_to do |format|
      if @truc.save
        format.html { redirect_to truc_url(@truc), notice: "Truc was successfully created." }
        format.json { render :show, status: :created, location: @truc }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @truc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trucs/1 or /trucs/1.json
  def update
    respond_to do |format|
      if @truc.update(truc_params)
        format.html { redirect_to truc_url(@truc), notice: "Truc was successfully updated." }
        format.json { render :show, status: :ok, location: @truc }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @truc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trucs/1 or /trucs/1.json
  def destroy
    @truc.destroy

    respond_to do |format|
      format.html { redirect_to trucs_url, notice: "Truc was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_truc
      @truc = Truc.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def truc_params
      params.require(:truc).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/trucs_helper.rb
module TrucsHelper
end

app/views/bars/_bar.html.erb
<div id="<%= dom_id bar %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= bar.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Adress:</strong>
    <%= bar.adress %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">City:</strong>
    <%= bar.city %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Cocktails associés :</strong></p>
    <ul>
      <% bar.cocktails.each do |cocktail| %>
      <li><%= cocktail.name %></li>
  <% end %>
    </ul>

  <% if action_name != "show" %>
    <%= link_to "Show this bar", bar, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this bar", edit_bar_path(bar), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/bars/_form.html.erb
<%= form_with(model: bar, class: "contents") do |form| %>
  <% if bar.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(bar.errors.count, "error") %> prohibited this bar from being saved:</h2>

      <ul>
        <% bar.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :adress %>
    <%= form.text_field :adress, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :city %>
    <%= form.text_field :city, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
<div class="my-5">
  <%= form_with(model: bar, local: true) do |form| %>

  <!-- Champ de sélection multiple pour les cocktails -->
  <%= form.label :cocktail_ids, "Choisissez les cocktails" %>
  <%= form.collection_select :cocktail_ids, Cocktail.all, :id, :name, {}, {multiple: true} %>
</div>
  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>



<% end %>

app/views/bars/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing bar</h1>

  <%= render "form", bar: @bar %>

  <%= link_to "Show this bar", @bar, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to bars", bars_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/bars/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Bars</h1>
    <%= link_to "New bar", new_bar_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="bars" class="min-w-full">
    <%= render @bars %>
  </div>
</div>

app/views/bars/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New bar</h1>

  <%= render "form", bar: @bar %>

  <%= link_to "Back to bars", bars_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/bars/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @bar %>

    <%= link_to "Edit this bar", edit_bar_path(@bar), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this bar", bar_path(@bar), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to bars", bars_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/cocktails/_cocktail.html.erb
<div id="<%= dom_id cocktail %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= cocktail.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= cocktail.description %>
  </p>
    <p class="my-5">
    <strong class="block font-medium mb-1">Price :</strong>
    <%= cocktail.prices.pluck(:value).sum %> €
  </p>
  
  <% if action_name != "show" %>
    <%= link_to "Show this cocktail", cocktail, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this cocktail", edit_cocktail_path(cocktail), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/cocktails/_form.html.erb
<%= form_with(model: cocktail, class: "contents") do |form| %>
  <% if cocktail.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(cocktail.errors.count, "error") %> prohibited this cocktail from being saved:</h2>

      <ul>
        <% cocktail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing cocktail</h1>

  <%= render "form", cocktail: @cocktail %>

  <%= link_to "Show this cocktail", @cocktail, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to cocktails", cocktails_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/cocktails/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Cocktails</h1>
    <%= link_to "New cocktail", new_cocktail_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="cocktails" class="min-w-full">
    <%= render @cocktails %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New cocktail</h1>

  <%= render "form", cocktail: @cocktail %>

  <%= link_to "Back to cocktails", cocktails_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/cocktails/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
<h2>Utilisateurs ayant noté ce cocktail:</h2>
<ul>
  <% @cocktail.users.each do |user| %>
    <li><%= user.email %> a donné la note de <%= user.notes.find_by(cocktail: @cocktail).value %></li>
  <% end %>
</ul>
    <%= render @cocktail %>
  
    <%= link_to "Edit this cocktail", edit_cocktail_path(@cocktail), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this cocktail", cocktail_path(@cocktail), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to cocktails", cocktails_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RomainCarvalho</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
    <% flash.each do |key, value| %>
  <div class="flash <%= key %>"><%= value %></div>
    <% end %>
  <body>

    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/trucs/_form.html.erb
<%= form_with(model: truc) do |form| %>
  <% if truc.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(truc.errors.count, "error") %> prohibited this truc from being saved:</h2>

      <ul>
        <% truc.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/trucs/_truc.html.erb
<div id="<%= dom_id truc %>">
  <p>
    <strong>Name:</strong>
    <%= truc.name %>
  </p>

</div>

app/views/trucs/edit.html.erb
<h1>Editing truc</h1>

<%= render "form", truc: @truc %>

<br>

<div>
  <%= link_to "Show this truc", @truc %> |
  <%= link_to "Back to trucs", trucs_path %>
</div>

app/views/trucs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Trucs</h1>

<div id="trucs">
  <% @trucs.each do |truc| %>
    <%= render truc %>
    <p>
      <%= link_to "Show this truc", truc %>
    </p>
  <% end %>
</div>

<%= link_to "New truc", new_truc_path %>

app/views/trucs/new.html.erb
<h1>New truc</h1>

<%= render "form", truc: @truc %>

<br>

<div>
  <%= link_to "Back to trucs", trucs_path %>
</div>

app/views/trucs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @truc %>

<div>
  <%= link_to "Edit this truc", edit_truc_path(@truc) %> |
  <%= link_to "Back to trucs", trucs_path %>

  <%= button_to "Destroy this truc", @truc, method: :delete %>
</div>